apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  dnsPolicy: ClusterFirst 
  containers:
    - name: docker-initial
      image: docker:25.0.3-cli  # Lightweight Docker CLI-only image
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      command: ["cat"]
      tty: true  
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket     
