apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  dnsPolicy: ClusterFirst 
  containers:
    - name: mvn
      image: maven:3.9.9
      command:
        - cat
      tty: true
    - name: docker
      image: dind:myversion
      securityContext:
        privileged: true  
    - name: helm
      image: alpine/helm:3.18
      command:
        - cat
      tty: true
    - name: docker-cli
      image: docker:25.0.3-cli  # Lightweight Docker CLI-only image
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      command: ["cat"]
      tty: true  
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket     
