apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  dnsPolicy: ClusterFirst 
  containers:
    - name: mvn
      image: maven:3.9.9
      command:
        - cat
      tty: true
    - name: docker
      image: custom-agent:myversion
      securityContext:
        privileged: true  
    - name: helm
      image: alpine/helm:3.18
      command:
        - cat
      tty: true
